### ISSUE TITLE
[Help] how to modify tx fee? 

### ISSUE THREAD

**Issue by yann-sjtu** [spoo-bar/cosmy-wasmy#23]
I found that the tx fee is `1 native token` by default, how can I use custom tx fee?

**Comment by spoo-bar** [comment]
Hey @yann-sjtu 
If you have installed the extension from the marketplace, you can change the gas price is the extension settings, but custom tx fees arent supported the released version yet.
If you are running the extension by building the latest source, the same sidebar view where you type the tx input, there is a fee box below to specify the tx fees. 1 native token is just the placeholder and you can replace that.

**Comment by yann-sjtu** [comment]
thanks~
