### ISSUE TITLE
cosmwasm-vm needs to be upgraded

### ISSUE THREAD

**Issue by aeryz** [spoo-bar/cosmy-wasmy#45]
The `cosmwasm-vm` that is used here is taken from  [here](https://github.com/hussein-aitlahcen/cosmwebwasm) I guess. Note that this `cosmwasm-vm` version is outdated, it contains some severe bugs (e.g. admin is incorrectly checked when doing migrate). And the vm implementation is missing some host functions so that if any contract call these, they will likely to be failed or run incorrectly. I would be happy to upgrade the vm implementation that will cover all of the host functions as well as using the most recent `cosmwasm-vm`.

**Comment by spoo-bar** [comment]
Thank you so much! However, the extension currently uses [@terran-one/cw-simulate](https://www.npmjs.com/package/@terran-one/cw-simulate) for the VM operations. Missed out on `cosmwebwasm` in the code cleanup 😓
