### ISSUE TITLE
Attribution is missing

### ISSUE THREAD

**Issue by KaiserKarel** [spoo-bar/cosmy-wasmy#46]
The cosmwasm-vm implementation used has not properly been attributed according to the license, meaning that currently the plugin cannot be used by developers and companies.

It's quite impolite and illegal, although I assume this was an honest mistake.

**Comment by KaiserKarel** [comment]
Actually the code used is unlicensed, meaning that currently the implementation is completely unusable until https://github.com/hussein-aitlahcen/cosmwebwasm/tree/master/pkg includes a license.

**Comment by spoo-bar** [comment]
Thank you so much for bringing this to my attention @KaiserKarel 

I missed handling this in code cleanup. The extension uses [@terran-one/cw-simulate](https://www.npmjs.com/package/@terran-one/cw-simulate) which is MIT licensed.

**Comment by KaiserKarel** [comment]
Ah all good, apologies for causing confusion then :).
