### ISSUE TITLE
After v2.2.0 is upgraded, it cannot be used on mac

### ISSUE THREAD

**Issue by zjg555543** [spoo-bar/cosmy-wasmy#59]
**Describe the bug**
After v2.2.0 is upgraded, it cannot be load on mac. But it's no problem when rollback to v2.1.0.
![1](https://user-images.githubusercontent.com/7919751/231369247-2f592a29-c764-4e41-a57a-15446ac22541.png)

![2](https://user-images.githubusercontent.com/7919751/231369679-14017e95-f4ba-4177-8b5c-875c6fc5b499.png)

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Version [e.g. 1.68.0]
 - Running vscode Insider [e.g yes/no]

**Additional context**

**Comment by spoo-bar** [comment]
Can you include the error log from the console?
You can get it at Help > Toggle Developer Tools > Console

**Comment by zjg555543** [comment]
![image](https://user-images.githubusercontent.com/7919751/231449444-1e9d372e-942d-472d-a8f2-09efcc3c2929.png)

**Comment by zjg555543** [comment]
I find the reason.By deleting bufferutil and utf-8-validate, then webpack and release angain,  it'will be success.
Can you release a new version again? Thanks~ 
```
webpack.config.js
bufferutil: "bufferutil",
"utf-8-validate": "utf-8-validate",
```
From https://github.com/spoo-bar/cosmy-wasmy/pull/51
