### ISSUE TITLE
Parsing integer Input error when running the Initialize operation

### ISSUE THREAD

**Issue by dauTT** [spoo-bar/cosmy-wasmy#8]
Good Job,
Thanks for making this extension.

I try it out for this increment contract:
https://github.com/archway-network/archway-templates/tree/main/increment

Query, Execute contract works fine but the Initialize operation doesn't work. It throw this error message:

![image](https://user-images.githubusercontent.com/30392990/177001194-a3d1e594-6a6c-4c64-babf-d2c6f69ef1fb.png)

Executing the command directly works fine:

```
junod tx wasm instantiate 1 '{"count": 100}' --from testAccount --label "Our third contract" --no-admin
```

Perhaps there is a problem with parsing the JSON?

**Comment by spoo-bar** [comment]
Thanks a lot for bringing it to my attention. 
Yea, it was a parsing error. 😅

This should be fixed in the latest version `v0.4.0`.
Let me know if you still face issues after updating  :)
