### ISSUE TITLE
ctrl+shift+h keybind overwrites default vscode find

### ISSUE THREAD

**Issue by Reecepbcups** [spoo-bar/cosmy-wasmy#9]
VSCode by default uses ctrl+shift+h to Replace in files & the most recent version overwrites that
https://github.com/spoo-bar/cosmy-wasmy/blob/main/package.json#L268-L270

Replace in Files | Ctrl+Shift+H | workbench.action.replaceInFiles
https://code.visualstudio.com/docs/getstarted/keybindings

While a fix is to put `{ "key": "ctrl+shift+h", "command": "workbench.action.replaceInFiles"}` in keybinds.json (per user basis), it likely makes more sense to try and use another keybind to not cause this issue for others

**Comment by spoo-bar** [comment]
Oops! Will change the default bindings. 
Thanks a lot for bringing it to my attention. :)
